import * as pdfjsLib from "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs";
pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs";
const $=id=>document.getElementById(id);let pdf=null,bytes=null,file=null,current=1,scale=.9,order=[],comments=[],redactions=[];
const input=$("pdfInput");$("uploadBtn").onclick=$("openWelcome").onclick=()=>input.click();input.onchange=e=>e.target.files[0]&&openPDF(e.target.files[0]);
async function openPDF(f){file=f;bytes=new Uint8Array(await f.arrayBuffer());pdf=await pdfjsLib.getDocument({data:bytes.slice()}).promise;order=Array.from({length:pdf.numPages},(_,i)=>i);current=1;$("docTitle").textContent=f.name+" - PDF Reader Web";$("welcome").classList.add("hidden");$("pdfScroll").classList.remove("hidden");await render();await thumbs();controls()}
function controls(){$("pageNo").value=current;$("pageCount").textContent=order.length;$("zoomLabel").textContent=Math.round(scale*100)+"%"}
async function render(){let p=$("pages");p.innerHTML="";for(let pos=0;pos<order.length;pos++){let w=document.createElement("div");w.className="pageWrap";w.dataset.pos=pos;let c=document.createElement("canvas");c.className="pdfCanvas";w.append(c);p.append(w);let pg=await pdf.getPage(order[pos]+1),v=pg.getViewport({scale});c.width=v.width;c.height=v.height;await pg.render({canvasContext:c.getContext("2d"),viewport:v}).promise}}
async function thumbs(){$("thumbs").innerHTML="";for(let i=0;i<order.length;i++){let d=document.createElement("div");d.className="thumb";d.dataset.pos=i;let c=document.createElement("canvas"),p=await pdf.getPage(order[i]+1),v=p.getViewport({scale:.18});c.width=v.width;c.height=v.height;await p.render({canvasContext:c.getContext("2d"),viewport:v}).promise;let n=document.createElement("div");n.className="thumbNum";n.textContent=i+1;d.append(c,n);d.onclick=()=>go(i);$("thumbs").append(d)}highlight()}
function highlight(){document.querySelectorAll(".thumb").forEach(x=>x.classList.toggle("active",+x.dataset.pos===current-1))}
function go(i){current=Math.max(1,Math.min(order.length,i+1));document.querySelector(`.pageWrap[data-pos="${current-1}"]`)?.scrollIntoView({behavior:"smooth"});controls();highlight()}
$("pageNo").onchange=e=>go(+e.target.value-1);$("prevBtn").onclick=()=>go(current-2);$("nextBtn").onclick=()=>go(current);
$("zoomIn").onclick=async()=>{scale=Math.min(2.5,scale+.1);await render();controls()};$("zoomOut").onclick=async()=>{scale=Math.max(.4,scale-.1);await render();controls()};$("zoomMenu").onclick=()=>{let n=prompt("Zoom percentage",Math.round(scale*100));if(n){scale=Math.max(.4,Math.min(3,+n/100));render();controls()}}
document.querySelectorAll(".rail").forEach(b=>b.onclick=()=>{document.querySelectorAll(".sideContent").forEach(x=>x.classList.add("hidden"));$(b.dataset.panel).classList.remove("hidden");document.querySelectorAll(".rail").forEach(x=>x.classList.remove("active"));b.classList.add("active")});
function toggle(id){$(id).classList.toggle("hidden")}
document.querySelectorAll(".tool").forEach(b=>b.onclick=()=>{let a=b.dataset.action;if(a==="export")toggle("exportMenu");else if(a==="create")toggle("createMenu");else if(a==="combine")$("multiInput").click();else if(a==="organize")organize();else if(a==="edit")edit();else if(a==="comment")comment();else if(a==="redact")redact()});
$("multiInput").onchange=async e=>{let fs=[...e.target.files];if(!fs.length)return;let out=await PDFLib.PDFDocument.create();for(let f of fs){let d=await PDFLib.PDFDocument.load(await f.arrayBuffer());(await out.copyPages(d,d.getPageIndices())).forEach(p=>out.addPage(p))}download(await out.save(),"combined.pdf","application/pdf")};
async function organize(){if(!pdf)return alert("Open a PDF first.");let cmd=prompt("Organize: DELETE, DUPLICATE, ROTATE, EXTRACT");if(!cmd)return;cmd=cmd.toLowerCase();if(cmd==="delete"&&order.length>1)order.splice(current-1,1);if(cmd==="duplicate"){order.splice(current,0,order[current-1]);current++}if(cmd==="rotate"){let d=await PDFLib.PDFDocument.load(bytes.slice()),p=d.getPage(order[current-1]);p.setRotation(PDFLib.degrees((p.getRotation().angle+90)%360));bytes=new Uint8Array(await d.save());pdf=await pdfjsLib.getDocument({data:bytes.slice()}).promise}if(cmd==="extract"){let d=await PDFLib.PDFDocument.load(bytes.slice()),o=await PDFLib.PDFDocument.create();o.addPage((await o.copyPages(d,[order[current-1]]))[0]);download(await o.save(),"extracted-page.pdf","application/pdf");return}current=Math.min(current,order.length);await render();await thumbs();controls()}
async function edit(){if(!pdf)return alert("Open a PDF first.");let text=prompt("Text to add to current page");if(!text)return;let d=await PDFLib.PDFDocument.load(bytes.slice()),p=d.getPage(order[current-1]),font=await d.embedFont(PDFLib.StandardFonts.Helvetica);p.drawText(text,{x:60,y:100,size:18,font});bytes=new Uint8Array(await d.save());pdf=await pdfjsLib.getDocument({data:bytes.slice()}).promise;await render();alert("Text added. Use Save/Download to export.") }
async function comment(){if(!pdf)return alert("Open a PDF first.");let text=prompt("Comment");if(!text)return;comments.push({page:current,text});alert("Comment added to this session.")}
async function redact(){if(!pdf)return alert("Open a PDF first.");let d=await PDFLib.PDFDocument.load(bytes.slice()),p=d.getPage(order[current-1]);p.drawRectangle({x:50,y:80,width:180,height:30,color:PDFLib.rgb(0,0,0)});bytes=new Uint8Array(await d.save());pdf=await pdfjsLib.getDocument({data:bytes.slice()}).promise;await render();alert("Redaction mark added to current page.")}
document.querySelectorAll("[data-convert]").forEach(b=>b.onclick=async()=>{if(!pdf)return alert("Open a PDF first.");let type=b.dataset.convert;if(type==="image"){for(let i=0;i<order.length;i++){let c=document.createElement("canvas"),p=await pdf.getPage(order[i]+1),v=p.getViewport({scale:1.5});c.width=v.width;c.height=v.height;await p.render({canvasContext:c.getContext("2d"),viewport:v}).promise;c.toBlob(x=>download(x,"page-"+(i+1)+".png","image/png"))}}else if(type==="word"){let h="<html><body>";for(let i=0;i<order.length;i++){let p=await pdf.getPage(order[i]+1),t=await p.getTextContent();h+="<h2>Page "+(i+1)+"</h2><p>"+t.items.map(x=>x.str).join(" ")+"</p>"}download(new Blob([h],{type:"application/msword"}),"converted.doc","application/msword")}else{let csv="Page,Text\n";for(let i=0;i<order.length;i++){let p=await pdf.getPage(order[i]+1),t=await p.getTextContent();csv+=(i+1)+',"'+t.items.map(x=>x.str).join(" ").replaceAll('"','""')+'"\n'}download(new Blob([csv],{type:"text/csv"}),"converted.csv","text/csv")}});
$("createFromFiles").onclick=()=>$("createInput").click();$("createInput").onchange=e=>{let fs=[...e.target.files];if(fs.length)alert("Create PDF from "+fs.length+" file(s) can be connected to the combine engine.")};
$("printBtn").onclick=()=>file&&window.open(URL.createObjectURL(file))?.print();$("shareBtn").onclick=()=>navigator.clipboard?.writeText(location.href).then(()=>alert("Web app link copied."));$("moreBtn").onclick=()=>alert("More tools: Fill & Sign, Organize Pages, Convert, Comment, Redact");
function download(data,name,type){let u=URL.createObjectURL(new Blob([data],{type})),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
